import adminVitePlugin from "@medusajs/admin-vite-plugin"
import react from "@vitejs/plugin-react"
import { resolve } from "path"
import { defineConfig } from "vite"

export default defineConfig({
  plugins: [
    react(),
    adminVitePlugin({
      sources: [resolve(__dirname, "src/admin")],
      pluginMode: true,
    }),
  ],
  build: {
    outDir: resolve(__dirname, ".medusa/server/src/admin"),
    emptyOutDir: false,
    lib: {
      // Generated by adminVitePlugin during buildStart
      entry: resolve(__dirname, "src/admin/__admin-extensions__.js"),
      formats: ["es"],
      fileName: "index",
    },
    rollupOptions: {
      external: [
        "react",
        "react/jsx-runtime",
        "react-dom",
        "@medusajs/ui",
        "@medusajs/admin-sdk",
        "@medusajs/admin-shared",
        "@medusajs/icons",
        "@medusajs/framework/types",
      ],
      output: {
        exports: "named",
      },
    },
  },
})
